#
# Copyright (C) 2013, BCM Advanced Research
#
# Authors: Frodo Lai <frodo_lai@bcmcom.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#
ifdef CONFIG_SPL_BUILD
obj-y = ar6mxcs_spl.o
else
obj-y = ar6mxcs.o
endif
